version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
      - backup-volume:/app/backups
    environment:
      - DOCKER_ENV=true
      - FLASK_ENV=production

volumes:
  backup-volume: